[17.0][ADD] product_category_pricelist_button
solvosci/slv-product pull request #18
Opened 2024-10-07 08:16 UTC by Anxo82

2024-10-07 08:17 UTC, Anxo82 commented
@dalonsod Review please.
Thanks

2024-10-08 17:00 UTC, dalonsod requested changes
See comments for suggested enhacements

2024-10-08 17:00 UTC, dalonsod commented on product_category_pricelist_button/models/product_category.py
> +            )
We'll try to obtain this count for every category in a more efficient way. Please take a look at this:

https://github.com/OCA/purchase-workflow/blob/8c0e713baac1d9a16356316a2fbfecf048ce46ec/purchase_order_type_dashboard/models/purchase_order_type.py#L32-L58

(purchase order count for certain purchase order types). This example is more complex than we require, please try to adapt it here (if find a simpler example I'll provide it anyway)

2024-10-08 17:00 UTC, dalonsod commented on product_category_pricelist_button/views/product_category_views.xml
> +    <record id="view_product_category_form_inherit" model="ir.ui.view">
Once items count is refactored please add that field to tree view

2024-10-09 13:35 UTC, Anxo82 commented
@dalonsod Review please.
Thanks

2024-10-09 15:17 UTC, dalonsod commented
@lmiguens-solvos form view, as expected:

![imagen](https://github.com/user-attachments/assets/f6877a88-6720-4b56-b1e9-87152d0f9108)


...but tree view is terribly simple:

![imagen](https://github.com/user-attachments/assets/9fcdfbd1-7a56-4459-8d43-6f3ca90800f4)

(@Anxo82 we should tell them as "Pricelist Items", not "Pricelists")

Would you need some extra features in this view, like highlighting those categories that have one ore more pricelist items, or some filters "With pricelist items" and "Without pricelist items"?

2024-10-09 15:26 UTC, lmiguens-solvos commented
It's okay, at the moment no more extra features are necessary. 
I also agree with the change ("Pricelist Items" for "Pricelists")) that you indicate.
And I'm waiting to see how that pricelist item tree view looks...

2024-10-10 07:03 UTC, Anxo82 commented
@dalonsod @lmiguens-solvos Review please.
Thanks

2024-10-10 07:40 UTC, dalonsod commented on product_category_pricelist_button/models/product_category.py
> +    def _compute_pricelist_count(self):
Once `pricelist_count` is now stored, an `@api.depends` clause should be added, could you make the required modifications?

2024-10-14 09:02 UTC, Anxo82 commented
@dalonsod Review please.
Thanks.

2024-10-14 13:25 UTC, dalonsod approved these changes
:+1: 

Please make those pending descriptions issues, generate `README` stuff, make squashes, and I'll merge it

2024-10-14 13:25 UTC, dalonsod commented on product_category_pricelist_button/__manifest__.py
> +        Adds a smart button to product categories linking to associated pricelists.
Pending items reference:
```suggestion
        Adds a smart button to product categories linking to associated pricelist items.
```

2024-10-14 13:25 UTC, dalonsod commented on product_category_pricelist_button/readme/DESCRIPTION.md
> +Adds a smart button to product categories linking to associated pricelists.
Here too:
```suggestion
Adds a smart button to product categories linking to associated pricelist items.
```

2024-10-14 13:40 UTC, Anxo82 commented
@dalonsod Done, review please.
Thanks

2024-10-14 14:30 UTC, merged