[17.0][ADD] product_pricelist_item_formula_visibility
solvosci/slv-product pull request #20
Opened 2024-10-17 07:34 UTC by Anxo82

2024-10-17 14:16 UTC, Anxo82 commented
@dalonsod Review please.
Thanks

2024-10-17 17:14 UTC, dalonsod requested changes
See comments and please attach screenshots as we can see final location of these new columns

2024-10-17 17:14 UTC, dalonsod commented on product_pricelist_item_formula_visibility/views/product_pricelist_item_views.xml
> +    <record id="product_pricelist_item_tree_view_inherit" model="ir.ui.view">
Remember also adding these columns in pricelist item list view within pricelist form (view `product.product_pricelist_view`)

2024-10-17 17:14 UTC, dalonsod commented on product_pricelist_item_formula_visibility/views/product_pricelist_item_views.xml
> +                <field name="base" invisible="compute_price != 'formula'"/>
Make both columns optional (show as default)

2024-10-18 06:42 UTC, Anxo82 commented
@dalonsod Review please.
Thanks

2024-10-18 12:23 UTC, dalonsod commented
@lmiguens-solvos does it fit requirements?

![imagen](https://github.com/user-attachments/assets/b1a46b58-ab48-45d6-9790-2da4edd906d4)

The same order in general pricelist item views...

2024-10-20 08:48 UTC, lmiguens-solvos commented
> @lmiguens-solvos does it fit requirements?
> 
> ![imagen](https://private-user-images.githubusercontent.com/12749832/377864761-b1a46b58-ab48-45d6-9790-2da4edd906d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MTQwODIsIm5iZiI6MTcyOTQxMzc4MiwicGF0aCI6Ii8xMjc0OTgzMi8zNzc4NjQ3NjEtYjFhNDZiNTgtYWI0OC00NWQ2LTk3OTAtMmRhNGVkZDkwNmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDA4NDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNjQ0MWFjZWEyMGZiZjdiNjgwM2EwZDgxMjAwYzU0OWIzYWNhZDhiMDBkYzE3ZDc2OTAxNmM3MWRkMDk0YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pSs62v4mkPXThH72iMWEFX5LnsgAC3m0swBvi3tEDX8)
> 
> The same order in general pricelist item views...

In the addon that adds coeficcient, the coefficient had been placed before the price column, so the "new" fields to be displayed would be between minimum quantity and price, and the order is fine: Calculation, Based on and Coefficient.

2024-10-21 07:29 UTC, Anxo82 commented
@lmiguens-solvos @dalonsod Changed, in original product_pricelist_item_tree_view, min_quantity is after the price, that's why the order is Computatio, Based on and coefficient.
Thanks

2024-10-23 11:03 UTC, dalonsod approved these changes
:+1: 

Please add the following pending stuff:
* Add missing `EOF` empty lines for both views .xml files:

  ![imagen](https://github.com/user-attachments/assets/2adc2806-a4d1-44b6-9b89-570575143cf9)

* Generate `README` files.
* Squash commits.

2024-10-23 11:25 UTC, Anxo82 commented
Done, review please.
Thanks

2024-10-23 13:49 UTC, dalonsod approved these changes
Ready to be merged!

2024-10-23 13:49 UTC, merged