[17.0][IMP] product_category_pricelist_button
solvosci/slv-product pull request #22
Opened 2024-10-28 14:59 UTC by Anxo82

Change string field, translations and new README.

2024-10-28 15:00 UTC, Anxo82 commented
@ChristianSantamaria @dalonsod Review please.
Thanks

2024-10-29 06:08 UTC, ChristianSantamaria requested changes
LGTM, only a improvement:

2024-10-29 06:08 UTC, ChristianSantamaria commented on product_category_pricelist_button/__manifest__.py
>      "license": "LGPL-3",
Miss manifest version

2024-10-29 08:23 UTC, Anxo82 commented
@ChristianSantamaria done!
Thanks

2024-11-06 15:27 UTC, dalonsod commented
Tested :+1: 

I've renamed commit and PR title. @Anxo82 for those `[IMP]` or `[FIX]` PR/commits extra information within main title is needed, "[IMP] addon_name" is not enough.

Let's merge...

2024-11-06 15:27 UTC, merged